# Generated by Django 3.0.6 on 2021-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='idmaquina',
            field=models.CharField(default='anything', max_length=10),
        ),
    ]
