# Generated by Django 3.1.6 on 2021-02-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0003_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avarias', models.CharField(max_length=255)),
                ('idmaquina', models.CharField(default='anything', max_length=10)),
            ],
        ),
    ]
