# Generated by Django 3.1.6 on 2021-02-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0005_informacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avarias',
            name='dataabertura',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='avarias',
            name='datafecho',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='avarias',
            name='estado',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='avarias',
            name='ot',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='avarias',
            name='planificador',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='avarias',
            name='problema',
            field=models.CharField(default='anything', max_length=100),
        ),
        migrations.AddField(
            model_name='avarias',
            name='solicitante',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='informacao',
            name='estadomaquina',
            field=models.CharField(default='anything', max_length=50),
        ),
    ]
