# Generated by Django 3.1.6 on 2021-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0006_auto_20210225_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='historico',
            new_name='avaria',
        ),
        migrations.AddField(
            model_name='historico',
            name='dataabertura',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='historico',
            name='datafecho',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='historico',
            name='planificador',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AddField(
            model_name='historico',
            name='problema',
            field=models.CharField(default='anything', max_length=100),
        ),
        migrations.AddField(
            model_name='historico',
            name='solicitante',
            field=models.CharField(default='anything', max_length=50),
        ),
    ]
