# Generated by Django 3.1.6 on 2021-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0007_auto_20210225_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='image',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/'),
        ),
    ]
