# Generated by Django 3.1.6 on 2021-03-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0008_informacao_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='doc',
            field=models.FileField(default='Doc/None/No-doc.pdf', upload_to='Doc/'),
        ),
    ]
