# Generated by Django 3.1.6 on 2021-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0009_informacao_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='video',
            field=models.FileField(default='Video/None/No-vid.mp4', upload_to='Video/'),
        ),
    ]
