# Generated by Django 3.1.6 on 2021-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0010_informacao_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacao',
            name='audio',
            field=models.FileField(default='Audio/None/No-aud.mp3', upload_to='Audio/'),
        ),
    ]
