# Generated by Django 3.1.3 on 2021-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0011_informacao_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.CharField(max_length=255)),
                ('idmaquina', models.CharField(default='anything', max_length=10)),
                ('passo', models.CharField(default='anything', max_length=50)),
                ('image', models.ImageField(default='Images/None/No-img.jpg', upload_to='Images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='informacao',
            name='audio',
        ),
    ]
