# Generated by Django 3.1.3 on 2021-05-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0012_auto_20210507_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotos',
            old_name='fotos',
            new_name='info',
        ),
    ]
